export const UserAction = {
  SET_USER_DATA: 'SET_USER_DATA',
  GET_LOCAL_SESSION: 'GET_LOCAL_SESSION',
  CLEAN_UP_USER: 'CLEAN_UP_USER',
  UPDTAE_USER_DATA: 'UPDTAE_USER_DATA',
  SET_USER_AFTER_UPDATE: 'SET_USER_AFTER_UPDATE',
};

export const UserScope = 'user';
