export const AppAction = {
  SHOWLIVECHAT: "SHOWLIVECHAT",
  HIDELIVECHAT: "HIDELIVECHAT",
  SHOWDEPOSIT: "SHOWDEPOSIT",
  HIDEDEPOSIT: "HIDEDEPOSIT",
  SHOWWITHDRAW: "SHOWWITHDRAW",
  HIDEWITHDRAW: "HIDEWITHDRAW",
};
