export const AppAction = {
  SHOWLIVECHAT: "SHOWLIVECHAT",
  HIDELIVECHAT: "HIDELIVECHAT",
  SHOWDEPOSIT: "SHOWDEPOSIT",
  HIDEDEPOSIT: "HIDEDEPOSIT",
  SHOWWITHDRAW: "SHOWWITHDRAW",
  HIDEWITHDRAW: "HIDEWITHDRAW",
  SET_GAMES_DATA: "SET_GAMES_DATA",
  SET_BANNERS_DATA: "SET_BANNERS_DATA",
};
